---
- hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      become: true
  
    - name: Install Spice
      ansible.builtin.apt:
        name: spice-vdagent
        state: present
      become: true
  
    - name: Start Spice
      systemd:
        state: started
        name: spice-vdagent
        enabled: yes
  
    - name: Fix Resolution
      ansible.builtin.shell: "xrandr --output Virtual-1 --mode 1600x900"

    - name: Add GPG key for VSCodium repo
      become: true
      ansible.builtin.shell: "wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg | gpg --dearmor | sudo dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg"
    
    - name: Add vscodium repo
      ansible.builtin.shell: "echo 'deb [ signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg ] https://download.vscodium.com/debs vscodium main' | sudo tee /etc/apt/sources.list.d/vscodium.list"
    
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      become: true

    - name: Install additional programs
      ansible.builtin.include_tasks:
        file: apps.yml

    - name: Copy torrc to guest
      ansible.builtin.shell: cp /vagrant/torrc /etc/tor/torrc && cp /vagrant/torsocks.conf /etc/tor/torsocks.conf
      become: true

    - name: Copy newsboat urls to guest
      shell: mkdir -p /home/vagrant/.newsboat && cp /vagrant/newsboat/urls /home/vagrant/.newsboat/urls
